services:
  - type: web
    name: plantripapc
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISK_PATH
        value: /data
    disk:
      name: plantrip-data
      mountPath: /data
      sizeGB: 1
